export const About = {
    "kind": "t2",
    "data": {
      "is_employee": false,
      "is_friend": false,
      "subreddit": {
        "default_set": true,
        "user_is_contributor": false,
        "banner_img": "https://styles.redditmedia.com/t5_7hg9h/styles/profileBanner_yv203r04fel11.jpg?width=1280&amp;height=384&amp;crop=1280:384,smart&amp;s=274fa8386333de9d264ccc2b10f4eab9a92bcdc8",
        "restrict_posting": true,
        "user_is_banned": false,
        "free_form_reports": true,
        "community_icon": null,
        "show_media": true,
        "icon_color": "",
        "user_is_muted": false,
        "display_name": "u_OmgImAlexis",
        "header_img": null,
        "title": "",
        "previous_names": [],
        "over_18": true,
        "icon_size": [
          256,
          256
        ],
        "primary_color": "",
        "icon_img": "https://styles.redditmedia.com/t5_7hg9h/styles/profileIcon_snoo0e44414a-5c17-4d81-8d55-fe3e8b50845b-headshot.png?width=256&amp;height=256&amp;crop=256:256,smart&amp;s=2a84a10865cfcab0a0fb104a143be9da38144cc9",
        "description": "",
        "submit_link_label": "",
        "header_size": null,
        "restrict_commenting": false,
        "subscribers": 0,
        "submit_text_label": "",
        "is_default_icon": false,
        "link_flair_position": "",
        "display_name_prefixed": "u/OmgImAlexis",
        "key_color": "",
        "name": "t5_7hg9h",
        "is_default_banner": false,
        "url": "/user/OmgImAlexis/",
        "quarantine": false,
        "banner_size": [
          1280,
          384
        ],
        "user_is_moderator": false,
        "public_description": "Instagram: @OmgImAlexis",
        "link_flair_enabled": false,
        "disable_contributor_requests": false,
        "subreddit_type": "user",
        "user_is_subscriber": false
      },
      "snoovatar_size": [
        380,
        600
      ],
      "awardee_karma": 461,
      "id": "f29oz",
      "verified": true,
      "is_gold": true,
      "is_mod": true,
      "awarder_karma": 10343,
      "has_verified_email": true,
      "icon_img": "https://styles.redditmedia.com/t5_7hg9h/styles/profileIcon_snoo0e44414a-5c17-4d81-8d55-fe3e8b50845b-headshot.png?width=256&amp;height=256&amp;crop=256:256,smart&amp;s=2a84a10865cfcab0a0fb104a143be9da38144cc9",
      "hide_from_robots": false,
      "link_karma": 25392,
      "pref_show_snoovatar": false,
      "total_karma": 45673,
      "accept_chats": false,
      "name": "OmgImAlexis",
      "created": 1391176276.0,
      "created_utc": 1391176276.0,
      "snoovatar_img": "https://i.redd.it/snoovatar/snoovatars/0e44414a-5c17-4d81-8d55-fe3e8b50845b.png",
      "comment_karma": 9477,
      "accept_followers": true,
      "has_subscribed": true,
      "accept_pms": true
    }
  };